language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
script:
- py.test --cov lrutils tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls